import os

# AWS 設定
AWS_IOT_ENDPOINT = 'YOUR_AWS_IOT_ENDPOINT'
AWS_IOT_THING_NAME = 'YOUR_AWS_IOT_THING_NAME'

# Certificates 設定
HOME_DIR = os.getcwd()
AWS_CERTS_PATH_BASE = HOME_DIR
AWS_CERTS_PATH_ROOTCA = AWS_CERTS_PATH_BASE + '/' + AWS_IOT_THING_NAME + '.root-CA.pem'
AWS_CERTS_PATH_PRIVATEKEY = AWS_CERTS_PATH_BASE + '/' + AWS_IOT_THING_NAME + '.private.key'
AWS_CERTS_PATH_CERTIFICATE = AWS_CERTS_PATH_BASE + '/' + AWS_IOT_THING_NAME + '.cert.pem'

# MQTT 設定
MQTT_DEVICE_ID = 'YOUR_DEVICE_ID'
MQTT_TOPIC = 'YOUR_TOPIC'
MQTT_QOS = 1

# Raspberry Pi 設定
I2C_BUS = 0x1

# センサデータの送信間隔（秒）
SEND_SENSORDATA_INTERVAL_SEC = 60
